
version: '3.7'

services:
  app:
    image: webapp:latest
    build: .
    ports:
     - 9000:80
    volumes:
     - .:/urlhome
    depends_on:
     - urldb
    deploy:
      replicas: 2
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - app
      - redis
      - lb

  urldb:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      redis:
          ipv4_address: 10.5.5.91
    volumes:
      - ./redis.conf:/urlhome/redis.conf
    command: [ "redis-server", "/urlhome/redis.conf" ]

  proxy:
    image: nginx:alpine
    ports:
      - published: 80
        target: 80
    depends_on:
      - app
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - lb
      - app

networks:
  lb:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
  app:
    ipam:
      driver: default
      config:
        - subnet: "10.4.5.0/24"

  redis:
    ipam:
      driver: default
      config:
        - subnet: "10.5.5.0/24"
